// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/jwt/hash.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIHashCrypto is a mock of IHashCrypto interface.
type MockIHashCrypto struct {
	ctrl     *gomock.Controller
	recorder *MockIHashCryptoMockRecorder
}

// MockIHashCryptoMockRecorder is the mock recorder for MockIHashCrypto.
type MockIHashCryptoMockRecorder struct {
	mock *MockIHashCrypto
}

// NewMockIHashCrypto creates a new mock instance.
func NewMockIHashCrypto(ctrl *gomock.Controller) *MockIHashCrypto {
	mock := &MockIHashCrypto{ctrl: ctrl}
	mock.recorder = &MockIHashCryptoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHashCrypto) EXPECT() *MockIHashCryptoMockRecorder {
	return m.recorder
}

// HashPassword mocks base method.
func (m *MockIHashCrypto) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockIHashCryptoMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockIHashCrypto)(nil).HashPassword), password)
}

// VerifyPassword mocks base method.
func (m *MockIHashCrypto) VerifyPassword(password, hash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", password, hash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockIHashCryptoMockRecorder) VerifyPassword(password, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockIHashCrypto)(nil).VerifyPassword), password, hash)
}
