// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/jwt/jwt.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockITokenManager is a mock of ITokenManager interface.
type MockITokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockITokenManagerMockRecorder
}

// MockITokenManagerMockRecorder is the mock recorder for MockITokenManager.
type MockITokenManagerMockRecorder struct {
	mock *MockITokenManager
}

// NewMockITokenManager creates a new mock instance.
func NewMockITokenManager(ctrl *gomock.Controller) *MockITokenManager {
	mock := &MockITokenManager{ctrl: ctrl}
	mock.recorder = &MockITokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenManager) EXPECT() *MockITokenManagerMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockITokenManager) CreateToken(username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockITokenManagerMockRecorder) CreateToken(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockITokenManager)(nil).CreateToken), username)
}

// VerifyToken mocks base method.
func (m *MockITokenManager) VerifyToken(tokenString string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenString)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockITokenManagerMockRecorder) VerifyToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockITokenManager)(nil).VerifyToken), tokenString)
}
