logger:
  level: 'info'
  file: 'logs.log'

http:
  port: 8080

database:
  driver: 'postgres'
  host: 'db'
  port: 5432
  user: 'postgres'
  password: 'password'
  dbname: 'shop'

jwt:
  key: 'TOKEN_EXAMPLE'